application: gaetracker
version: 1
runtime: python
api_version: 1

handlers:

- url: /tracker
  script: gaetracker
  login: admin
- url: /gae-tracker/static/
  static_dir: gaetracker/static

builtins:
- datastore_admin: on
